alter table dbsdk_v1.CONF activate row access control;
CREATE or replace PERMISSION dbsdk_v1.MYROWONLY ON dbsdk_v1.CONF FOR ROWS 
WHERE USRPRF = CURRENT_USER 
   OR CURRENT_USER IN ('DBSDK_V1')
ENFORCED FOR ALL ACCESS ENABLE;